### ISSUE TITLE
Upgrading using cilium CNI to Kubernetes 1.23.3 leads to problems

### ISSUE THREAD

**Issue by exolab** [kubermatic/kubeone#1870] opened 2022-02-21 15:31 UTC
**What happened**:
After upgrading to 1.23.3 on Hetzner I see hcloud-csi-nodes caught in a CrashLoopBackoff on all control plane nodes
```
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  15m                 default-scheduler  Successfully assigned kube-system/hcloud-csi-node-45r2p to prod-001-control-plane-3
  Normal   Pulled     15m                 kubelet            Container image "k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0" already present on machine
  Normal   Created    15m                 kubelet            Created container csi-node-driver-registrar
  Normal   Started    15m                 kubelet            Started container csi-node-driver-registrar
  Normal   Pulled     15m                 kubelet            Successfully pulled image "docker.io/hetznercloud/hcloud-csi-driver:1.6.0" in 1.03741359s
  Normal   Pulling    15m                 kubelet            Pulling image "k8s.gcr.io/sig-storage/livenessprobe:v2.4.0"
  Normal   Pulled     15m                 kubelet            Successfully pulled image "k8s.gcr.io/sig-storage/livenessprobe:v2.4.0" in 412.469459ms
  Normal   Created    15m                 kubelet            Created container liveness-probe
  Normal   Started    15m                 kubelet            Started container liveness-probe
  Warning  Unhealthy  14m                 kubelet            Liveness probe failed: Get "http://10.244.2.54:9808/healthz": dial tcp 10.244.2.54:9808: i/o timeout (Client.Timeout exceeded while awaiting headers)
  Normal   Pulling    14m (x2 over 15m)   kubelet            Pulling image "docker.io/hetznercloud/hcloud-csi-driver:1.6.0"
  Normal   Killing    14m                 kubelet            Container hcloud-csi-driver failed liveness probe, will be restarted
  Normal   Created    14m (x2 over 15m)   kubelet            Created container hcloud-csi-driver
  Normal   Started    14m (x2 over 15m)   kubelet            Started container hcloud-csi-driver
  Normal   Pulled     14m                 kubelet            Successfully pulled image "docker.io/hetznercloud/hcloud-csi-driver:1.6.0" in 1.039115037s
  Warning  Unhealthy  10m (x30 over 14m)  kubelet            Liveness probe failed: Get "http://10.244.2.54:9808/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    8s (x55 over 13m)   kubelet            Back-off restarting failed container
```

...and machine-controller failing:
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  19m                   default-scheduler  Successfully assigned kube-system/machine-controller-77d6cfb8f7-kmxxf to prod-001-control-plane-3
  Normal   Killing    19m                   kubelet            Container machine-controller failed liveness probe, will be restarted
  Normal   Created    19m (x2 over 19m)     kubelet            Created container machine-controller
  Normal   Started    19m (x2 over 19m)     kubelet            Started container machine-controller
  Warning  Unhealthy  19m (x14 over 19m)    kubelet            Readiness probe failed: Get "http://10.244.2.162:8085/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  18m (x4 over 19m)     kubelet            Liveness probe failed: Get "http://10.244.2.162:8085/readyz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Normal   Pulled     14m (x7 over 19m)     kubelet            Container image "docker.io/kubermatic/machine-controller:v1.43.0" already present on machine
  Warning  BackOff    4m34s (x51 over 17m)  kubelet            Back-off restarting failed container

```

...as well as core-dns on the control plane
```
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Normal   Scheduled         23m                   default-scheduler  Successfully assigned kube-system/coredns-79c48b58b-nzvjn to prod-001-control-plane-3
  Normal   Pulled            23m                   kubelet            Container image "k8s.gcr.io/coredns/coredns:v1.8.6" already present on machine
  Normal   Created           23m                   kubelet            Created container coredns
  Normal   Started           23m                   kubelet            Started container coredns
  Warning  Unhealthy         21m (x4 over 22m)     kubelet            Liveness probe failed: Get "http://10.244.2.87:8080/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy         13m (x83 over 23m)    kubelet            Readiness probe failed: Get "http://10.244.2.87:8181/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  DNSConfigForming  3m19s (x64 over 23m)  kubelet            Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 2a01:4ff:ff00::add:1 2a01:4ff:ff00::add:2 185.12.64.2

``` 
...and cluster-autoscaler

```
 F0221 15:27:39.795533       1 main.go:420] Failed to get nodes from apiserver: Get "https://10.96.0.1:443/api/v1/nodes": dial tcp 10.96.0.1:443: i/o timeout 
```

I suppose I am overlooking something?

**What is the expected behavior**:

**How to reproduce the issue**:
1. Deploy a 1.22.7 cluster to Hetzner.
2. Update to 1.23.3

**Information about the environment**:
KubeOne version (`kubeone version`): 1.4.0 
Operating system: Ubuntu
Provider you're deploying cluster on: Hetzner

**Comment by exolab** [comment] 2022-02-21 15:35
Meant to create a support request, sorry.

**Comment by exolab** [comment] 2022-02-21 15:54
Sure:

```
                                            READY   STATUS             RESTARTS         AGE
cilium-bcz7k                                       1/1     Running            0                107m
cilium-l4txt                                       1/1     Running            0                107m
cilium-m4mcz                                       1/1     Running            0                104m
cilium-mlkjq                                       1/1     Running            0                107m
cilium-operator-f7866fc57-kjnz5                    1/1     Running            0                75m
cluster-autoscaler-8568767cf4-xrjh9                0/1     CrashLoopBackOff   17 (4m17s ago)   75m
coredns-79c48b58b-2cvl9                            1/1     Running            0                49m
coredns-79c48b58b-nzvjn                            0/1     Running            14 (5m34s ago)   49m
etcd-prod-001-control-plane-1                      1/1     Running            1 (79m ago)      79m
etcd-prod-001-control-plane-2                      1/1     Running            1 (76m ago)      76m
etcd-prod-001-control-plane-3                      1/1     Running            1 (72m ago)      72m
hcloud-cloud-controller-manager-8799f6667-6g79h    1/1     Running            0                82m
hcloud-csi-controller-0                            5/5     Running            0                82m
hcloud-csi-node-2zndz                              2/3     CrashLoopBackOff   19 (2m3s ago)    46m
hcloud-csi-node-45r2p                              2/3     CrashLoopBackOff   19 (117s ago)    46m
hcloud-csi-node-cfgv8                              2/3     CrashLoopBackOff   19 (81s ago)     46m
hcloud-csi-node-k5b45                              3/3     Running            0                104m
hubble-relay-7944bf4846-9krft                      1/1     Running            0                107m
hubble-ui-75db46f59c-mz2zc                         3/3     Running            0                107m
kube-apiserver-prod-001-control-plane-1            1/1     Running            1 (79m ago)      79m
kube-apiserver-prod-001-control-plane-2            1/1     Running            1 (76m ago)      76m
kube-apiserver-prod-001-control-plane-3            1/1     Running            1 (72m ago)      72m
kube-controller-manager-prod-001-control-plane-1   1/1     Running            0                72m
kube-controller-manager-prod-001-control-plane-2   1/1     Running            0                72m
kube-controller-manager-prod-001-control-plane-3   1/1     Running            0                72m
kube-proxy-g8z4d                                   1/1     Running            0                80m
kube-proxy-ldl6s                                   1/1     Running            0                80m
kube-proxy-vr9dn                                   1/1     Running            0                80m
kube-proxy-wrkrl                                   1/1     Running            0                80m
kube-scheduler-prod-001-control-plane-1            1/1     Running            0                79m
kube-scheduler-prod-001-control-plane-2            1/1     Running            1 (76m ago)      76m
kube-scheduler-prod-001-control-plane-3            1/1     Running            0                72m
machine-controller-77d6cfb8f7-kmxxf                0/1     CrashLoopBackOff   19 (2m46s ago)   48m
machine-controller-webhook-8477bccb4b-bzqgq        0/1     CrashLoopBackOff   29 (4m12s ago)   75m
metrics-server-6bd949fccd-gjdvn                    1/1     Running            0                79m
node-local-dns-5dz7c                               1/1     Running            0                107m
node-local-dns-99d8h                               1/1     Running            0                104m
node-local-dns-dvtrq                               1/1     Running            0                107m
node-local-dns-jll7x                               1/1     Running            0                107m
```

**Comment by ahmedwaleedmalik** [comment] 2022-02-22 09:39
Hi @exolab, I tried reproducing it at my end but couldn't. Can you please share the following:

- KubeOneCluster manifest
- Output of`kubectl logs machine-controller-77d6cfb8f7-kmxxf -n kube-system`

**Comment by exolab** [comment] 2022-02-22 09:54
Manifest:
```
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
    kubernetes: 1.23.3
cloudProvider:
  hetzner: {}
  external: true
clusterNetwork:
  cni:
    # Only one CNI plugin can be defined at the same time
    # Supported CNI plugins:
    # * canal
    # * weave-net
    # * cilium
    # * external - The CNI plugin can be installed as an addon or manually
    cilium:
      # enableHubble to deploy Hubble relay and UI
      enableHubble: true
      # kubeProxyReplacement defines weather cilium relies on underlying Kernel support to replace kube-proxy functionality by eBPF (strict),
      # or disables a subset of those features so cilium does not bail out if the kernel support is missing (disabled).
      kubeProxyReplacement: "disabled"
# containerRuntime:
#   containerd: {}
addons:
  enable: true
  path: "./addons_prod-001"
```
Logs:

```
W0222 09:53:13.133152       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0222 09:53:13.133347       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0222 09:53:29.511807       1 main.go:295] caught signal, shutting down...
```

**Comment by exolab** [comment] 2022-02-23 08:13
This probably is better

```
W0223 08:07:03.106318       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0223 08:07:03.106449       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0223 08:07:19.523477       1 main.go:295] caught signal, shutting down...
F0223 08:07:33.110377       1 main.go:301] failed to create runtime manager: error building ctrlruntime manager: Get "https://10.96.0.1:443/api?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout
Stream closed EOF for kube-system/machine-controller-77d6cfb8f7-kmxxf (machine-controller)
```

**Comment by ahmedwaleedmalik** [comment] 2022-02-23 08:54
That is a transient error caused by broken networking in your cluster. We were able to reproduce this issue and **are currently investigating this**.

Just to confirm everything, can you please check the following:
- `kubectl logs -f hcloud-csi-node-2zndz -c liveness-probe -n kube-system` will be logging out`Still connecting to unix:///run/csi/socket`
- `kubectl exec -it cilium-l4txt -- cilium status --all-addresses | grep health`  should show that `cilium-health-ep` is not healthy.

This can also be linked with https://github.com/kubermatic/kubeone/issues/1744

**Comment by exolab** [comment] 2022-02-23 09:00
I can confirm both points and have also found the DNS problem in our logs...


```
cilium status --all-addresses | grep health
Cilium health daemon:   Ok
  10.244.0.130 (health)
Controller Status:   26/27 healthy
  cilium-health-ep   42h22m56s ago   5m3s ago     522     Get "http://10.244.0.130:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Cluster health:   4/4 reachable   (2022-02-23T08:57:30Z)
```

**Comment by ahmedwaleedmalik** [comment] 2022-02-23 09:06
I'd recommend you to contact Hetzner support for this. Meanwhile, we are working on a possible fix for this from our side.

**Comment by mdll** [comment] 2022-05-30 06:01
Has anybody a solution for that? I still have that problem on deploying k8s on Hetzner

**Comment by kron4eg** [comment] 2022-05-30 09:01
@mdll please see https://github.com/kubermatic/kubeone/issues/2021

**Closed** 2022-07-06 07:19 UTC
Labels: kind/bug, lifecycle/rotten, sig/cluster-management
