### ISSUE TITLE
AWS AutoScaling Group Support for Control Plane / Workers

### ISSUE THREAD

**Issue by cmoone** [kubermatic/kubeone#780] opened 2020-01-31 14:55 UTC
**What feature would you like to be added?**
Please add an option to configure KubeOne to build either standalone servers (current implementation) or allow users to configure control plane, workers, or both to run as autoscaled instance groups (requested feature).

**What are use cases of the feature?**
This would allow me to stand up a scalable High Availability cluster, which with my stateless application will greatly reduce costs and minimize ongoing maintenance.

**Comment by kron4eg** [comment] 2020-01-31 15:01
I'd call this issue a duplicate of https://github.com/kubermatic/kubeone/issues/391
Since worker nodes are governed by machine-controller, we hope to get autoscaler from the upstream. At the moment however the upstream PR https://github.com/kubernetes/autoscaler/pull/1866 is blocked.

@xmudrii WDYT?

**Comment by cmoone** [comment] 2020-01-31 15:06
@kron4eg my understanding of cluster-autoscaler is that you must have your nodes running in an autoscaling group for it to effectively scale nodes up or down.

**Comment by kron4eg** [comment] 2020-01-31 15:07
@cmoone in current state — yes, but with that pending PR the CA will get ClusterAPI support and that will unlock all supported clouds, and independent from presence of ASG functionality at provider side, so quite powerful thing to have :)

**Comment by cmoone** [comment] 2020-01-31 15:18
@kron4eg sounds amazing. Thanks for that explanation. Feel free to close as this seems duplicative.

**Comment by kron4eg** [comment] 2020-01-31 16:31
closed as dup of https://github.com/kubermatic/kubeone/issues/391

**Closed by kron4eg** 2020-01-31 16:31 UTC
Labels: kind/feature
