### ISSUE TITLE
install failed on openstack

### ISSUE THREAD

**Issue by pennpeng** [kubermatic/kubeone#590] opened 2019-07-17 08:31 UTC
**Information about the environment**:
KubeOne version (`kubeone version`): 0.9.2
Operating system: centos 7.6
Provider you're deploying cluster on: openstack
Operating system you're deploying on: centos 7.6

LOG：
```
[root@harbor openstack]# kubeone install config.yaml --tfjson tf.json
INFO[15:41:13 CST] Installing prerequisites…                    
INFO[15:41:13 CST] Determine operating system…                   node=172.18.24.137
INFO[15:41:13 CST] Determine hostname…                           node=172.18.24.137
INFO[15:41:13 CST] Creating environment file…                    node=172.18.24.137
INFO[15:41:14 CST] Installing kubeadm…                           node=172.18.24.137 os=centos
INFO[15:41:14 CST] Deploying configuration files…                node=172.18.24.137 os=centos
INFO[15:41:14 CST] Generating kubeadm config file…              
INFO[15:41:14 CST] Configuring certs and etcd on first controller… 
INFO[15:41:14 CST] Ensuring Certificates…                        node=172.18.24.137
INFO[15:41:14 CST] Downloading PKI files…                        node=172.18.24.137
INFO[15:41:15 CST] Creating local backup…                        node=172.18.24.137
INFO[15:41:15 CST] Deploying PKI…                               
INFO[15:41:15 CST] Configuring certs and etcd on consecutive controller… 
INFO[15:41:15 CST] Initializing Kubernetes on leader…           
INFO[15:41:15 CST] Running kubeadm…                              node=172.18.24.137
INFO[15:41:15 CST] Joining controlplane node…                   
INFO[15:41:15 CST] Copying Kubeconfig to home directory…         node=172.18.24.137
INFO[15:41:15 CST] Building Kubernetes clientset…               
INFO[15:41:15 CST] Creating credentials secret…                 
INFO[15:41:15 CST] Applying weave-net CNI plugin…               
INFO[15:41:15 CST] Installing machine-controller…               
INFO[15:41:15 CST] Installing machine-controller webhooks…      
INFO[15:41:15 CST] Waiting for machine-controller to come up…   
INFO[15:41:35 CST] Creating worker machines…                    
WARN[15:41:36 CST] Task failed, retrying…                       
INFO[15:41:41 CST] Creating worker machines…                    
WARN[15:41:42 CST] Task failed, retrying…                       
INFO[15:41:52 CST] Creating worker machines…                    
WARN[15:41:53 CST] Task failed, retrying…                       
Error: failed to create worker machines: failed to deploy Machines: failed to ensure MachineDeployment: Internal error occurred: admission webhook "machine-controller.kubermatic.io-machinedeployments" denied the request: defaulting or validation failed: failed to default machineSpec: failed to default network, due to 3 candidate networks found
Usage:
  kubeone install <manifest> [flags]

Examples:
kubeone install mycluster.yaml -t terraformoutput.json

Flags:
  -b, --backup string   path to where the PKI backup .tar.gz file should be placed (default: location of cluster config file)
  -h, --help            help for install

Global Flags:
  -d, --debug                           debug
  -t, --tfjson terraform output -json   Source for terrafor output JSON. - to read from stdin. If path is file, contents will be used. If path is dictionary, terraform output -json is executed in this path
  -v, --verbose                         verbose

failed to create worker machines: failed to deploy Machines: failed to ensure MachineDeployment: Internal error occurred: admission webhook "machine-controller.kubermatic.io-machinedeployments" denied the request: defaulting or validation failed: failed to default machineSpec: failed to default network, due to 3 candidate networks found

```

**Comment by xmudrii** [comment] 2019-07-17 08:57
Hello @pennpeng 

The issue seems to be related to creating the worker nodes:
```
INFO[15:41:35 CST] Creating worker machines…                    
WARN[15:41:36 CST] Task failed, retrying…                       
```

And the reason for the error seems to be:

```
defaulting or validation failed: failed to default machineSpec: failed to default network, due to 3 candidate networks found
```

In other words, there are 3 networks found, but `machine-controller` is not sure which one to choose.

This can be fixed by updating workers definition to set the network you want to use ([example](https://github.com/kubermatic/machine-controller/blob/master/examples/openstack-machinedeployment.yaml#L100-L101)). To set the network, add the `network` key to `cloudProviderSpec` part of the worker definition.

If you're using our example Terraform scripts, workers are defined in the [`output.tf` file](https://github.com/kubermatic/kubeone/blob/master/examples/terraform/openstack/output.tf#L56-L74).

**Comment by pennpeng** [comment] 2019-07-17 10:17
@xmudrii  how do i defined workers in  output.tf file.

**Comment by xmudrii** [comment] 2019-07-17 12:47
@pennpeng Sorry, I'm not sure I understand, but if you're using [example Terraform scripts](https://github.com/kubermatic/kubeone/tree/master/examples/terraform/openstack), one worker will be created by default and it's defined [here](https://github.com/kubermatic/kubeone/blob/master/examples/terraform/openstack/output.tf#L42-L79).

In case of that worker, it should be using [this network](https://github.com/kubermatic/kubeone/blob/master/examples/terraform/openstack/main.tf#L30-L33), so check if it is created and is everything okay.

Workers can also be manually defined. If you're using the configuration manifest from the [quickstart guide](https://github.com/kubermatic/kubeone/blob/master/docs/quickstart-openstack.md#installing-kubernetes), then you need to update it with details about your infrastructure, networks, and so on.

If the problem is still not solved or you encounter some other problem, please let us know.

**Comment by pennpeng** [comment] 2019-07-18 02:54
@xmudrii  thanks so much。i  manually defined is ok。 i want ask is there other network support ，like flannel？calico？and so on。and， is this can offline install？

**Comment by pennpeng** [comment] 2019-07-18 03:00
and how i specify  a docker version？

**Comment by kron4eg** [comment] 2019-07-18 07:23
@pennpeng 

networks: you can choose bentween cancal (flannel + calico) or weave-net.
offline install: not currently.
docker version: we don't allow that. If you really need to have specific docker version, you'd need to create custom image with docker pre-installed.

**Comment by kron4eg** [comment] 2019-08-09 14:38
I'll close this issue since it looks like the question is answered. If you feel like some more info is needed feel free to reopen.

**Closed by kron4eg** 2019-08-09 14:38 UTC
Labels: kind/question
