### ISSUE TITLE
Cluster Upgrade: dpkg error leading to retry for every node

### ISSUE THREAD

**Issue by jwerner-mt** [kubermatic/kubeone#1926] opened 2022-04-05 10:40 UTC
**What happened**:

During a cluster upgrade from K8s 1.21.8 (deployed using KubeOne 1.3.3) to 1.21.10 (using KubeOne 1.4.1), we had some issues. On all three nodes, the `containerd` upgrade failed the first time, leading to a retry.

```
WARN[11:40:38 CEST] Task failed, error was: failed to upgrade kubernetes binaries on leader control plane: + export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin:/usr/local/bin:/opt/bin
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin:/usr/local/bin:/opt/bin
+ sudo swapoff -a
+ sudo sed -i '/.*swap.*/d' /etc/fstab
+ sudo systemctl disable --now ufw
Synchronizing state of ufw.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable ufw
+ source /etc/kubeone/proxy-env
+ sudo tee /etc/modules-load.d/containerd.conf
+ cat
+ sudo modprobe overlay
+ sudo modprobe br_netfilter
+ sudo modprobe ip_tables
+ sudo mkdir -p /etc/sysctl.d
+ sudo tee /etc/sysctl.d/k8s.conf
+ cat
+ sudo sysctl --system
sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument
+ sudo mkdir -p /etc/systemd/journald.conf.d
+ cat
+ sudo tee /etc/systemd/journald.conf.d/max_disk_use.conf
+ sudo systemctl force-reload systemd-journald
+ sudo mkdir -p /etc/apt/apt.conf.d
+ cat
+ sudo tee /etc/apt/apt.conf.d/proxy.conf
+ sudo apt-get update
+ sudo DEBIAN_FRONTEND=noninteractive apt-get install --option Dpkg::Options::=--force-confold -y --no-install-recommends apt-transport-https ca-certificates curl gnupg lsb-release rsync
+ curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg
+ sudo apt-key add -
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ echo 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
+ sudo tee /etc/apt/sources.list.d/kubernetes.list
+ sudo apt-get update
+ kube_ver='1.21.10*'
+ cni_ver='0.8.7*'
+ sudo apt-mark unhold kubelet kubeadm kubectl kubernetes-cni
+ sudo apt-get update
+ sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common lsb-release
+ sudo apt-key add -
+ curl -fsSL https://download.docker.com/linux/ubuntu/gpg
Warning: apt-key output should not be parsed (stdout is not a terminal)
++ lsb_release -cs
+ sudo add-apt-repository 'deb https://download.docker.com/linux/ubuntu focal stable'
+ sudo apt-mark unhold containerd.io
+ sudo apt-get install -y 'containerd.io=1.4.*'
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
E: Sub-process /usr/bin/dpkg returned an error code (1)
: Process exited with status 100
WARN[11:40:43 CEST] Retrying task...
```

From `/var/log/apt/term.log`:

```
Log started: 2022-04-05  09:50:31
(Reading database ... 37145 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.4.13-1_amd64.deb ...
Unpacking containerd.io (1.4.13-1) over (1.4.12-1) ...
Setting up containerd.io (1.4.13-1) ...

Configuration file '/etc/containerd/config.toml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** config.toml (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package containerd.io (--configure):
 end of file on stdin at conffile prompt
Processing triggers for man-db (2.9.1-1) ...
Errors were encountered while processing:
 containerd.io
Log ended: 2022-04-05  09:50:36

Log started: 2022-04-05  09:53:26
Setting up containerd.io (1.4.13-1) ...

Configuration file '/etc/containerd/config.toml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
 ==> Using current old file as you requested.
Log ended: 2022-04-05  09:53:27
```

**What is the expected behavior**:

`containerd` update should succeed on the first try.

**Information about the environment**:
KubeOne version (`kubeone version`): 1.4.1
Operating system: Ubuntu 20.04
Provider you're deploying cluster on: Hetzner
Operating system you're deploying on: Ubuntu 20.04

**Comment by kron4eg** [comment] 2022-04-05 14:45
@jwerner-mt hey, thanks for the report. The problem is identified and soon the fix will be merged.

**Closed** 2022-04-05 17:04 UTC
Labels: kind/bug, sig/cluster-management
