### ISSUE TITLE
[GCE E2E tests] Terraform is unable to remove routes created by CCM

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#836] opened 2020-03-24 17:35 UTC
The GCE E2E tests are failing because Terraform can't remove routes created by Kubernetes CCM.
```
Error: Error waiting for Deleting Network: The network resource 'projects/project-name/global/networks/network-name' is already being used by 'projects/project-name/global/routes/route-name'
```

We need to find a way to remove routes created by the CCM, so Terraform can proceed with deleting the network.

Besides that, it seems like we are reaching limits:
```
Error: Error waiting for instance to create: Quota 'IN_USE_ADDRESSES' exceeded.  Limit: <limit> in region <region>.
```

**Acceptance criteria**

* Routes are removed before running Terraform
* Check what we can do about the limits

**Comment by youssefazrak** [comment] 2020-11-19 09:22
Terraform is not able to handle those routes, and without that, we can't have GCE E2E tests. Alternatively, we could eventually have some scripts that would remove those routes, but the problem is that we didn't really like having some external script.
As discussed with @xmudrii, closing it for now.

**Closed by youssefazrak** 2020-11-19 09:22 UTC
Labels: kind/bug, kind/failing-test, lifecycle/frozen, priority/high, team/lifecycle
