### ISSUE TITLE
Add terraform modules to the registry

### ISSUE THREAD

**Issue by eqrx** [kubermatic/kubeone#581] opened 2019-07-15 10:02 UTC
**What feature would you like to be added?**
Add the Terraform modules to https://registry.terraform.io/

**What are use cases of the feature?**
Users don't need to clone our repo to use the Terraform example.

**Comment by xmudrii** [comment] 2019-07-15 14:39
@eqrx This issue seems to be duplicate of #374

**Comment by kron4eg** [comment] 2019-07-16 15:39
indeed it is.

**Closed by kron4eg** 2019-07-16 15:39 UTC
Labels: kind/feature
