### ISSUE TITLE
Provide Example/Template/Document to Include Static Workers in Terraform Output

### ISSUE THREAD

**Issue by ag1989** [kubermatic/kubeone#1021] opened 2020-08-05 10:52 UTC
**What feature would you like to be added?**

While the included terraform examples can write the control_plane nodes as static output, they don't cover static worker nodes. Instead they include templates/definitions for the cloud provider to be used with machine-controller. In case machine-controller is not used for any reasons, the user has to manually edit the kubeone manifest and add the static workers. Therefore, inclusion of static-workers output in the template would be very useful in ordere to avoid manual editing of config files.

A quick and dirty solution could be to include documentation on what kind of input can be provided from terraform output and how it has to be formatted in order to allow kubeone to use it during k8s-cluster deployment. 

**What are use cases of the feature?**

- Testing of a future bare metal deployment in a cloud environment
- If a user does not want/cannot use machine-controller in its cloud deployment
- If a private cloud installation does not support some features

**Comment by kron4eg** [comment] 2020-08-05 11:56
Static workers was retrofitted as a feature later, and was intended for the environments where "there is no cloud", that's the reason why we don't have them in terraform examples, nether in terraform parsing code. If there is no cloud, there is no API to talk to via the terraform. And if you do have cloud, the machine-controller will always be 10 times better alternative then static workers.

@xmudrii I tend to reject and close this issue, WDYT?

**Comment by xmudrii** [comment] 2020-08-05 12:30
> A quick and dirty solution could be to include documentation on what kind of input can be provided from terraform output and how it has to be formatted in order to allow kubeone to use it during k8s-cluster deployment.

We are already working on a documentation update and we are planning to include some more details about how the integration works and what are supported options.

> I tend to reject and close this issue, WDYT?

I agree that where Terraform (Integration) is supported, it's highly advised to use machine-controller instead. Usually, when you need static workers, you can't even use the Terraform Integration, so adding static workers parsing doesn't sound very useful. However, on the other hand, it might be useful if someone prefers not to use the machine-controller, but in that case, I'd like to better understand what's the reasoning behind that. On top of that, I think we might need this if we decide to E2E test static workers (which we should consider as part of #839).

**Comment by ag1989** [comment] 2020-08-05 17:14
@xmudrii I am currently using it to test a Kubermatic deployment on our private OpenStack infrastructure which will later be deployed on our VMware infra (in case we go on with Kubermatic). In general I would fully agree with @kron4eg, however, our VMware is more or less working in a "bare metal" fashion, not allowing to use the machine-controller and other nice features (which I would love to use). In addition I cannot create VMs on my own in the VMware due to several constrains.

So my use case is that for trying out Kubermatic I use terraform to quickly create and/or kill hosts and network setups in our OpenStack infrastructure, which mimics a later deployment on our VMware. I don't know if others have the similar use cases but I thought it might be nice to have this as an option. As a workaround I use terraform's template engine what is fine but I thought there might be some way to do this with the terraform input.

**Comment by kron4eg** [comment] 2020-08-05 17:23
But kubermatic hard-depends on machine-controller... We use it for both, kubeone and kubermatic. And if on kubeone one can get away without using machine-controller, it's not the case for kubermatic.

**Comment by ag1989** [comment] 2020-08-05 18:08
@kron4eg sorry for the (probably dump) question but if I understand it right, but this would disqualifies kubermatic for use on on premise bare metal infrastructures? In our case it would only be the master/seed cluster that runs on VMware, user cluster would use OpenStack and therefore can make use of machine-controller. Maybe we close this issue and shift the discussion to slack?

**Comment by scheeles** [comment] 2020-08-06 07:35
@ag1989 statement from @kron4eg is not fully correct. You can add machine on provider which the machine-controller is not  supported based on a simple `kubeadm join` setup.

**Comment by scheeles** [comment] 2020-08-06 07:37
I think the idea make sense for providers where we don't have machine-controller but terraform support. With this you can create easy and cluster based on terraform and static worker.

@kron4eg what do you think?

**Comment by xmulligan** [comment] 2020-08-06 09:00
@ag1989 would it be helpful to move this conversation into Slack to discuss your exact use case? We actually have three different options that may fit, but we are not sure which would be best. 

Using the kubevirt provider ontop of static bare metal provisioned seed cluster
The kubeadm integration @scheeles mentioned above
Using the metal3 provider

if you want you can join our slack here and we can make a channel for you http://slack.kubermatic.io/

**Comment by ag1989** [comment] 2020-08-06 09:06
@scheeles thanks for your reply, this is what I found before in the kubermatic UI and config files and configured for our test seed cluster, therefore I was rather confused by @kron4eg who mentioned that machine-controller is a hard dependency.

@xmulligan I already joined the channel, will contact you soon :)

However, thank you all for the discussion!

**Closed** 2020-11-19 12:37 UTC
Labels: kind/feature
